FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    rustc \
    cargo

RUN mkdir /app
WORKDIR /app

EXPOSE 80

COPY ./services/ui ./app
RUN pip install --no-cache-dir flask==3.1.2 flask-cors==6.0.1 Flask-WTF==1.2.2 \
    requests==2.32.5 email-validator==2.3.0

COPY ./libs/login ./login
RUN pip install --no-cache-dir flask==3.1.2

COPY ./libs/jwt_token ./jwt_token
RUN pip install --no-cache-dir pyjwt[crypto]==2.10.1 requests==2.32.5

COPY ./libs/clients ./clients

ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENV PYTHONUNBUFFERED=1

CMD ["flask", "--app=app", "run", "--host=0.0.0.0", "--port=80"]
