services:
  postgresql_db:
    image: postgres:16.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data 
 
  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: bg@gmail.com
  #    PGADMIN_DEFAULT_PASSWORD: postgres
  #  ports:
  #    - "5454:80"
  #  volumes:
  #    - ./pgadmin:/var/lib/pgadmin

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  
  ui:
    image: ui
    build:
      context: .
      dockerfile: ./services/ui/Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./services/ui:/app/app # hot-reload
    #depends_on:
    #  idp:
    #    condition: service_healthy
    
  #data_gateway:
  #  image: data-gateway
  #  build:
  #    context: .
  #    dockerfile: services/data_gateway/Dockerfile
  #  environment:
  #    MINIO_ENDPOINT: minio:9000
  #    MINIO_ROOT_USER: minio
  #    MINIO_ROOT_PASSWORD: minio123
  
  #worker:
  #  image: worker
  #  build:
  #    context: .
  #    dockerfile: services/video_worker/Dockerfile
  
  idp:
    image: idp
    build:
      context: .
      dockerfile: ./services/IdP/Dockerfile.dev
    environment:
      - DATABASE_URI=postgresql://test:test@postgresql_db:5432/test
    ports:
      - 5000:80
    volumes:
      - ./data/IdP-rsa:/app/app/rsa # key pair
      - ./services/IdP:/app/app # hot-reload
    #healthcheck:
    #  test: ["CMD", "curl --fail http://idp/public_key || exit 1"]
    #  interval: 2s
    #  timeout: 5s
    #  retries: 3
    #  start_period: 5s
