services:
  redis: 
    image: redis:7-alpine
    container_name: redis
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  postgresql_db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    #environment:
    #  RABBITMQ_DEFAULT_USER: test
    #  RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 15s
      retries: 3
 
  adminer:
        image: adminer:latest
        ports: 
          - 98:8080

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  
  mongo:
      image: mongo
      restart: always
      logging:
          options:
              max-size: 1g
      environment:
          - MONGO_INITDB_ROOT_USERNAME=mongoadmin
          - MONGO_INITDB_ROOT_PASSWORD=bdung
      volumes:
      - ./data/mongo/init:/docker-entrypoint-initdb.d
      - ./data/mongo/db:/data/db
      - ./data/mongo/configdb:/data/configdb
      - ./data/mongo/mongot:/data/mongot

  ui:
    image: ui
    build:
      context: .
      dockerfile: ./services/ui/Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./services/ui:/app/app # hot-reload
    #depends_on:
    #  idp:
    #    condition: service_healthy
    
  data_gateway:
    image: data-gateway
    build:
      context: .
      dockerfile: services/data_gateway/Dockerfile
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      DATABASE_URI: postgresql://test:test@postgresql_db:5432/test
    ports:
      - 33:80
  
  worker:
    image: worker
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    environment:
      RABBITMQ_URI: 
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  idp:
    image: idp
    build:
      context: .
      dockerfile: ./services/IdP/Dockerfile.dev
    environment:
      DATABASE_URI: postgresql://test:test@postgresql_db:5432/test
    ports:
      - 5000:80
    volumes:
      - ./data/IdP-rsa:/app/app/rsa # key pair
      - ./services/IdP:/app/app # hot-reload

  registry:
    image: service_registry
    build:
      context: .
      dockerfile: ./services/service_registry/Dockerfile.dev
  
  worker_manager:
    image: worker_manager
    build:
      context: .
      dockerfile: ./services/worker_manager/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
