services:
  postgresql_db:
    image: postgres:16.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data 
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    #environment:
    #  RABBITMQ_DEFAULT_USER: admin
    #  RABBITMQ_DEFAULT_PASS: secure_password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 15s
      retries: 3

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  
  ui:
    image: ui
    build:
      context: .
      dockerfile: ./services/ui/Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./services/ui:/app/app # hot-reload
    #depends_on:
    #  idp:
    #    condition: service_healthy
    
  data_gateway:
    image: data-gateway
    build:
      context: .
      dockerfile: services/data_gateway/Dockerfile
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      DATABASE_URI: postgresql://test:test@postgresql_db:5432/test
    ports:
      - 33:80
  
  worker:
    image: worker
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  idp:
    image: idp
    build:
      context: .
      dockerfile: ./services/IdP/Dockerfile.dev
    environment:
      - DATABASE_URI=postgresql://test:test@postgresql_db:5432/test
    ports:
      - 5000:80
    volumes:
      - ./data/IdP-rsa:/app/app/rsa # key pair
      - ./services/IdP:/app/app # hot-reload

  registry:
    image: service_registry
    build:
      context: .
      dockerfile: ./services/service_registry/Dockerfile.dev
  
  worker_manager:
    image: worker_manager
    build:
      context: .
      dockerfile: ./services/worker_manager/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
