services:
  postgresql_db:
    image: postgres:16.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./instance:/var/lib/postgresql/data 
 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: bg@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5454:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: ./app/Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./app:/app/app
    
  #data_gateway:
  #  image: data-gateway
  #  build:
  #    context: .
  #    dockerfile: services/data_gateway/Dockerfile
  #  environment:
  #    MINIO_ENDPOINT: minio:9000
  #    MINIO_ROOT_USER: minio
  #    MINIO_ROOT_PASSWORD: minio123
  
  #worker:
  #  image: worker
  #  build:
  #    context: .
  #    dockerfile: services/video_worker/Dockerfile
  
  auth_authority:
    image: auth_authority
    build:
      context: .
      dockerfile: services/auth_authority/Dockerfile
    environment:
      - DATABASE_URI=postgresql://test:test@postgresql_db:5432/test
    ports:
      - 5000:80
    volumes:
      - ./services/auth_authority/rsa:/auth_authority/rsa
 
volumes:
  postgresql_data:
  minio_data:
