services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: ./app/Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    
  #postgres:
  #  image: postgres:16.3
  #  restart: always
  #  ports:
  #    - 5432:5432
  #  environment:
  #    POSTGRES_USER: myuser
  #    POSTGRES_DB: mydb
  #    POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
  #  secrets:
  #    - pg_password
  #  volumes:
  #    - ./instance:/var/lib/postgresql/data
    #networks:
    #  - private

  postgresql_db:
    image: postgres:16.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./instance:/var/lib/postgresql/data 
 
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    
  data_gateway:
    image: data-gateway
    build:
      context: .
      dockerfile: helper-services/data_gateway/Dockerfile
    ports:
      - 8282:8282
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
  
  worker:
    image: worker
    build:
      context: .
      dockerfile: helper-services/video_worker/Dockerfile
    ports:
      - 4242:4242
 
volumes:
  postgresql_data:
  minio_data:
