FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    rustc \
    cargo

RUN mkdir /app
WORKDIR /app

EXPOSE 80

COPY ./services/IdP ./app
RUN pip install --no-cache-dir fastapi==0.128.0 uvicorn==0.38.0 \
    sqlalchemy==2.0.44 psycopg2-binary==2.9.11 \
    cryptography==46.0.3 bcrypt==5.0.0 validators==0.35.0

COPY ./libs/jwt_token ./jwt_token
RUN pip install --no-cache-dir pyjwt[crypto]==2.10.1 requests==2.32.5

COPY ./libs/models ./models
RUN pip install --no-cache-dir sqlalchemy==2.0.44

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]
