FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    rustc \
    cargo

RUN mkdir /app
WORKDIR /app

EXPOSE 80

COPY r.txt .
RUN pip install --no-cache-dir -r r.txt

COPY ./app ./app
COPY ./models/login ./login
COPY ./models/jwt_token ./jwt_token

ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENV PYTHONUNBUFFERED=1

CMD ["flask", "--app=app", "run", "--host=0.0.0.0", "--port=80"]
