FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    rustc \
    cargo

RUN mkdir /app
WORKDIR /app

EXPOSE 80

COPY ./services/service_registry ./app
RUN pip install --no-cache-dir fastapi==0.128.0 uvicorn==0.38.0 requests==2.32.5

COPY ./libs/async_worker ./async_worker

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]
